### ISSUE TITLE
[Build] Windows CUDA 13.2 build fails in candle-kernels due to missing /Zc:preprocessor for MSVC

### ISSUE THREAD

**Issue by peterrobot** [mayocream/koharu#680]
When building Koharu from source on Windows with CUDA enabled, the build fails while compiling `candle-kernels v0.9.2`.

The failure happens in the CUDA kernel build step, specifically when `nvcc` compiles `src\reduce.cu`. CUDA 13.2's CCCL headers reject the MSVC traditional preprocessor mode and require `/Zc:preprocessor` to be passed to `cl.exe`.

Adding the following environment variable fixes the build:

```powershell
$env:NVCC_APPEND_FLAGS="-Xcompiler=/Zc:preprocessor"
````

This looks like a Windows + CUDA 13.2 + MSVC compatibility issue in the CUDA build flags rather than a general source-code problem. The same codebase can compile on Ubuntu with CUDA Toolkit 13.2.1.

## Steps to reproduce

1. Use Windows with CUDA Toolkit 13.2 installed.
2. Build Koharu with CUDA enabled.

## Actual behavior

The build fails in `candle-kernels v0.9.2` during the custom build script.

Relevant build information:

```text
candle-kernels v0.9.2
cuda_root: Some("C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2")
compute_cap: Some(80)
extra_args: []
```

The failing `nvcc` command does not include any MSVC preprocessor compatibility flag such as `-Xcompiler=/Zc:preprocessor`.

Relevant error:

```text
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.2\bin/./include/cccl\cuda/std/__cccl/preprocessor.h(20):
fatal error C1189:
#error: MSVC/cl.exe with traditional preprocessor is used.
Please switch to the standard conforming preprocessor by passing `/Zc:preprocessor` to cl.exe.
```

Then `bindgen_cuda` panics:

```text
thread 'main' panicked at ... bindgen_cuda-0.1.6\src\lib.rs:405:13
nvcc error while compiling "src\\reduce.cu"
```

## Expected behavior

Koharu should build successfully with CUDA enabled on Windows when using a supported CUDA 13.x toolkit and MSVC toolchain.

The CUDA kernel build should pass the required MSVC preprocessor flag when building with CUDA 13.2 or newer CCCL headers.

## Confirmed workaround

The following workaround fixes the build in my environment:

```powershell
$env:NVCC_PREPEND_FLAGS="-std=c++17"
$env:NVCC_APPEND_FLAGS="-Xcompiler=/Zc:preprocessor"
$env:CUDA_COMPUTE_CAP="80"

cargo clean -p candle-kernels
bun run dev
```

## Suggested fix

One possible fix is to add the required flag for Windows CUDA builds, for example in `.cargo/config.toml`:

```toml
[env]
NVCC_APPEND_FLAGS = "-Xcompiler=/Zc:preprocessor"
```

Alternatively, the build script or development script could detect Windows + CUDA 13.2+ and append the flag automatically before invoking `nvcc`.

For example, the effective `nvcc` command should include something equivalent to:

```text
-Xcompiler=/Zc:preprocessor
```

## Environment

```text
OS: Windows 11
Target: x86_64-pc-windows-msvc
CUDA Toolkit: 13.2
CUDA compute capability: 80
MSVC: Visual Studio 18 Community, MSVC 14.50.35717
Rust toolchain: nightly-x86_64-pc-windows-msvc
Build command: bun run dev
Failing crate: candle-kernels v0.9.2
Failing CUDA file: src\reduce.cu
```

**Comment by mayocream** [comment]
Please install CUDA 13.0 instead
